    
- Todos somos obrigados a lidar com dinheiro. Simplesmente não há escolha. Todos lidam com dinheiro, dos mais abastados ao mais desafortunados.  
- 3 faces do dinheiro  
	- Entrave - A falta do dinheiro impede você de realizar coisas que deseja. É a face do dinheiro em escassez. Pode ser uma falta direta de dinheiro para comprar algo... Ou mais sutil, como a incapacidade de estudar ou mudar de área já que precisa continuar procurando pelo sustento.  
	- Catapulta -  o dinheiro é capaz de potencializar nossas vidas, nos impulsionar na direção das coisas que queremos. É possível conquistar diversas coisas com pouco ou nenhum dinheiro, mas tê-lo acelera o processo.  
	- Corrimão - algumas situações da vida seguem seu curso natural, sem impulsos. Nessas situações, ter um aporte financeiro garante segurança para tomar decisões mais acertadas, permitindo manter as coisas organizadas e até financiar pequenas experimentações enquanto não se tem um plano bem definido.  
- Tipos de gastos  
	- Fixos - São gastos previsíveis, geralmente mensais  
	- Variáveis - são gastos, geralmente mensais, mas que mudam ao longo do tempo. O autor aconselha olhar para esses gastos sob uma ótica semanal para ficar mais fácil prever e controlar.  
	- Sazonais - Gastos que pagamos de tempos em tempos. Semestrais ou anuais. Tais gastos muitas vezes passam despercebidos no planejamento financeiro e podem causar quedas consideráveis quando se aproximam.  
	- Imprevistos - são gastos quase impossíveis de prever pois podem ocorrer a qualquer momento e impactar muito negativamente o planejamento financeiro. A melhor maneira de se preparar para eles é fazendo uma reserva e utilizando uma margem. O autor recomenda que o dinheiro para imprevistos deve corresponder a 15% do seu gasto médio mensal. A ideia é economizar mensalmente esse valor. Nem todo mês tudo será gasto, mas alguns meses podem compensar outros.  
- Diagnóstico financeiro  
	- O autor recomenda fazer uma espécie de diagnóstico financeiro, analisando seus gastos sempre que você se sentir inseguro quanto a como gasta seu dinheiro, mas ao menos uma vez por mês.  
	- Esse diagnóstico inclui elencar todas as suas fontes de renda e seus gastos financeiros, separando-os pelas categorias citadas.  
	- O diagnóstico permite que você consiga enxergar melhor possibilidades de mudanças e sugere priorizar gastos que lhe trazem conforto e qualidade de vida e eliminar gastos que não trazem retorno ou não fazem sentido na sua realidade atual.  
	- Dentro desse diagnóstico ele traz o conceito de "variável da semana" que é uma quantidade de dinheiro semanal que cobre seus gastos variáveis todos, sem que você precise ficar elencando um por um e tornando seu diagnóstico cansativo. É uma aproximação.  
- Planejamento financeiro  
	- Tendo esse diagnóstico em mãos, sugere realizar um planejamento financeiro que terá como base um mês, dividido em 4 semanas. Como ele gosta de papel, divide uma folha em 4 quadrantes.  
	- Nesse planejamento, ele coloca o saldo inicial da semana, as receitas previstas para aquela semana, as despesas fixas e sazonais previstas para aquela semana e o "variável da semana". Com isso, faz com que seja possível prever quanto você terá de saldo ao fim de cada semana e assim, ao fim do mês.  
	- Variável da semana  
		- O "variável da semana" é uma espécie de custo da sua semana. Quanto a sua semana custa para ser vivida de forma agradável.  
		- Ele aconselha a sacar esse variável da semana. Mas eu entendo que talvez a sugestão seja separá-lo do restante do seu dinheiro para conseguir acompanhar mais de perto. A ideia é sentir o dinheiro sendo gasto.  
		- Aconselha que se possa sacar mais dinheiro caso seja necessário, mas que se isso estiver se repetindo, talvez seja hora de reavaliar esses gastos variáveis para definir se deve passar a sacar mais dinheiro ou se tem algum gasto que possa ser reduzido  
		- Ainda, afirma que, caso sobre dinheiro do variável da semana, você possa se recompensar por isso.  
		- Afirma ainda que não é interessante sacar diferentes valores a cada semana. A ideia é meter o mesmo valor fixo na tentativa de "fixar" seus gastos variáveis. A regularidade desse valor faz com que a semana encaixe nele.  
		- O variável da semana não é destinado a cobrir gastos imprevistos.  
	- Apatia financeira  
		- Muitas vezes não realizamos o planejamento financeiro porque somos tomados por uma apatia financeira. Uma sensação ruim com relação ao dinheiro.  
		- Motivos para apatia financeira  
			- Ilusão de que o planejamento financeiro é algo complexo e dolorido  
			- Crença orgulhosa de que tudo vai dar certo  
			- Medo de se perceber incapaz de lidar as possíveis restrições que o planejamento trará  
			- Visão limitada a respeito das possibilidades que o dinheiro traz  
	- Crie sua reserva de emergência  
		- Trate aportes para a reserva de emergência como um gasto fixo mensal  
		- Faça o mesmo com outras reservas para outros objetivos.  
		- Prefira usar valores fixos para esses aportes. Se você perceber que em algum mês consegue guardar 500, mas no outro consegue 300... Já deixe os 300 como um gasto programado.  
	- Causas de falha de planejamento  
		- Complexidade - muito detalhamento deixa as coisas difíceis e cansativas  
		- Excesso de Rigidez - um planejamento sufocante só serve para ser abandonado à primeira vista. É como uma dieta muito rígida, fácil de idealizar, impossível de manter.  
			- Estimativas fantasiosas  
			- Não ter espaço no orçamento para pequenos prazeres da vida  
			- Não ter uma margem para imprevistos  
		- Falta de organização na vida - pensar em dinheiro é pensar na própria vida. Uma rotina caótica dificulta o planejamento de qualquer coisa, especialmente do dinheiro.  
		- Falta de motivo para o planejamento existir - o dinheiro é uma ferramenta para conseguir coisas na vida. Para ele existir, é preciso ter um impulso para conquistar alguma coisa. Se não há ímpeto suficiente, o planejamento não faz muito sentido. Os objetivos devem ser mensuráveis.  
	- Como aumentar as chances de sucesso do seu planejamento  
		- Automatize as ações benéficas - Exemplo: você sempre poupa 200 reais mensais. Automatize essa transferência. Se você tem a opção de colocar coisas no débito automático, faça isso.  
		- Eliminar cascas de banana, em vez de desviar delas - resolva os problemas e anteveja novos problemas semelhantes. Realize manutenções para evitar problemas. Avalie seus hábitos de consumo e elimine riscos, compras que você faz que te causam sentimentos de arrependimento, crie mecanismos contra elas.  
- Cartão de crédito  
	- O cartão de crédito é um empréstimo e deve ser tratado como tal.  
	- Muita gente usa o cartão de crédito como uma extensão da conta corrente e isso causa desorganização das contas porque joga os pagamentos para momentos futuros.  
	- Você não deve tratar o cartão como uma despesa fixa - você não deve cartão... O cartão é uma forma de pagamento, não uma conta.  
	- Faça de tudo para não usar o parcelamento da fatura do cartão  
	- O cartão é bem utilizado se for feito para reunir compras recorrentes e diminuir a burocracia das contas.  
- Investimentos  
	- Poupar é uma maneira de conseguir comprar coisas além da sua capacidade financeira mensal  
	- Investir é utilizar parte de um recurso para obter um retorno em um determinado prazo  
	- Conceitos importantes  
		- CDI  
			- Bancos emprestam dinheiro entre si, diariamente. Esse empréstimo diário é um CDI, certificado de depósito bancário.  
			- No fim do dia, a média do CDI gera uma taxa. E a média mensal dessas médias diárias também é calculada. Essa informação é pública.  
			- Esse CDI serve como índice para muitos investimentos.  
		- Rentabilidade  
			- É a quantidade de dinheiro ganho quando se coloca ele em um investimento  
			- Para ter alguma rentabilidade, é necessário se expor ao risco de perder dinheiro.  
			- Investimentos com menores riscos, têm menor rentabilidade  
		- Liquidez  
			- A capacidade de transformar um investimento de volta em dinheiro. A rapidez com que isso é possível.  
			- Alguns investimentos têm liquidez diária, mas geralmente têm menor rendimento.  
			- Liquidez baixa demais também pode representar um risco se você precisar daquele dinheiro logo. Uma reserva de emergência diminui a chance disso acontecer.  
		- Juros compostos  
			- Juro é o dinheiro que você ganha ao emprestar dinheiro a alguém  
			- Juros compostos é receber juros sobre juros de uma aplicação inicial ao passar do tempo  
		- Inflação - a variação do poder de compra do dinheiro.  
		- Juro real - rendimento do seu investimento, subtraído da inflação. Quanto você ganha de verdade em um investimento.  
	- Previdência privada  
		- Depender somente do INSS é incerto e provavelmente não será suficiente para uma velhice feliz  
		- Procure planos sem taxa de carregamento e saída, cuja taxa de administração seja a menor possível  
		- O site da Susep mostra todas as instituições que podem fazer previdência privada  
		- A maior vantagem é que a previdência privada te obriga a economizar. Mas existem opções bem melhores e mais flexíveis de investimento  
		- Não faz sentido contribuir para uma previdência privada se você estiver mal das pernas, devendo. Ela não é uma reserva de emergência  
	- Títulos de capitalização  
		- É uma ferramenta que te obriga a poupar dinheiro, impossibilitando saque. Em troca, te oferece uns sorteios.  
		- Na prática, o título de capitalização é uma loteria que reembolsa o valor apostado (corrigido abaixo da inflação) após alguns meses. Não é investimento. Você perde dinheiro por conta da inflação.  
	- Poupança  
		- Rende abaixo da inflação, mas não cobra IOF  
		- Pode ser útil apenas para separar um montante pequeno que vai ser usado em breve da conta corrente  
- Casa própria x Aluguel  
	- Financeiramente, aluguel é superior e traz diversas vantagens, especialmente quando se é jovem.  
	- Ter uma casa pode trazer um sentimento de segurança.  
	- Financiar uma casa custa caro e pode atrapalhar seus planos de investimento  
	- Cada uma das decisões tem seus prós e seus contras. A parte emocional influência muito.  
- Dinheiro marital  
	- Geralmente, a gente vive com outra pessoa, mas não é íntimo o suficiente pra falar sobre dinheiro (e sobre várias outras coisas).  
	- Falar sobre dinheiro pode ajudar a esclarecer melhor os planos e perspectivas de futuro  
	- Custo-casal é o conceito que o autor traz para o dinheiro que é gasto mensalmente em conjunto  
	- Ele propõe a existência de uma configuração financeira em 3 contas. 2 correntes, individuais, e outra conjunta, na qual será depositado mensalmente o custo-casal  
	- Ele propõe uma divisão proporcional de acordo com os ganhos mensais dos parceiros, mas afirma também que outras configurações são possíveis, contanto que abertamente negociadas.  
	- Contribuir com mais, não deve significar poder decidir de forma prioritária, em detrimento do outro. A conta conjunta é uma questão logística, não decisória. As decisões do dinheiro conjunto devem ser conjuntas.  
	- Excedentes podem ser pagos por um dos dois do casal, contanto que voluntariamente  
	- Se um dos dois cônjuges se dedica ao cuidado dos filhos, o cônjuge provedor deve continuar contribuindo para a conta conjunta e pagar uma "mesada" para o cônjuge que abriu mão de sua carreira por conta dos filhos. Mas mesmo nessa configuração, é interessante que cada cônjuge tenha sua conta individual.  
	- A ausência de uma conta conjunta bagunça a conta de um dos dois. A ausência de uma conta individual para um dos cônjuges cria uma ferramenta de vigilância dos gastos do outro.  
	- Converse com seu parceiro sobre seus objetivos financeiros e de vida. A felicidade que vocês perseguem é a mesma, mas podem tomar formas distintas e caminhos distintos  
	- É normal que suas tarefas/papeis não sejam os mesmos, mas complementares.  
	- Confie na inteligência do outro. Seus saberes não são os mesmos. Tire proveito das habilidades de cada um. Inteligência de beneficia de diversidade.  
- Dívidas  
	- Dívidas e empréstimos são a mesma coisa. Todos nós já devemos dinheiro de alguma maneira. Parcelamento também é dívida  
	- Se na hora de investir, os juros compostos trabalham ao nosso favor... Na hora de tomar dinheiro emprestado trabalham contra e com bastante disposição  
	- Fuja veementemente de empréstimos pessoais. Taxas de juros exorbitantes te jogam facilmente numa bola de neve de dívidas  
	- Quando se está endividado, é normal sentir medo das dividas. Especialmente se forem múltiplas. Mas é preciso encarar as dividas e ter clareza delas. Mantendo o inimigo bem visível.  
	- Coloque suas dívidas no papel. Anote parcelas, taxas de juros de cada uma delas e montante total.  
	- Uma alternativa é trocar uma dívida composta de várias partes por um empréstimo único, mais fácil de gerenciar. Com parcelas fixas.  
	- Mas antes de fazer um empréstimo, é importante mudar os hábitos, senão ele será apenas uma dívida a mais  
	- Calcule o montante total necessário para quitar suas dívidas e comece a poupar para conseguir esse dinheiro. Pague primeiro as dívidas mais agressivas  
	- Se for pedir um empréstimo, adicione no cálculo do total necessário um percentual extra, já que imprevistos continuarão acontecendo. O autor usou 20%. Esse é o valor do empréstimo que você precisa. Deixe esse excedente na poupança, como o início de sua reserva de emergência.  
	- Calcule as parcelas que consegue aguentar no mês.  
	- Vá no banco pessoalmente pedir o empréstimo. As taxas são menores assim. Cooperativas de crédito geralmente são melhores que bancos.  
	- Garanta, no ato da contratação, que sua modalidade de empréstimo permite amortizar, pagar adiantado parcelas, se sobrar dinheiro.  
	- Calcule quanto dinheiro vai perder e use isso como motivador para sair do ciclo de endividamento.  
	- Enquanto a dívida existir, você deve viver com o mínimo existencial e pagar a dívida.  
	- Se preciso for, feche as torneiras. Não confie no seu auto-controle. Vá lá e cancele cheque especial e cartão de crédito. Se não for possível, reduza seu limite a 25% do atual.  
	- Não vale a pena deixar uma dívida prescrever. Após 5 anos, ela não vai sumir, só a empresa vai perder o direito de cobrar. Mas até lá, será um inferno.  
	- Tente negociar sua dívida com a instituição  
	- Caso a dívida tenha sofrido juros abusivos, procure um consultor financeiro, como por exemplo o instituto nacional de defesa dos consumidores do sistema financeiro  
	- Trocar uma dívida mais cara por uma dívida mais barata vale a pena, mas deve fazer parte de um planejamento para não ter dívida nenhuma  
	- Dívidas entre familiares ou amigos devem existir somente se a relação entre vocês possa resistir a não serem pagas.  
- Repense sua vida financeira  
	- Precifique seus sonhos  
		- Quando for planejar, quebre o sonho em etapas  
		- Pense no quanto vai custar cada etapa. Isso cria um plano que torna mais fácil a realização.  
		- Seu plano não precisa ser perfeito, é um esboço que pode ser adaptado ao decorrer do tempo. Faça estimativas.  
		- Some tudo  
		- Tente ver quais ações pode tomar para realizar o sonho. Sem descartar ideias incomuns.  
		- Mostre seu plano pra alguém de confiança pra que essa pessoa possa ajudar a refinar  
	- Explique sua vida financeira para alguém em um minuto  
		- Manter a vida financeira simples e clara é aumentar as chances de dar certo  
		- Quanto mais você praticar falar sobre sua vida financeira, mais fácil vai ser e mais insights vai colher  
- Como seguir adiante  
	- Tanto tentar mudar tudo de uma só vez quanto não começar é ruim  
	- Tentar mudar tudo não se sustenta  
	- Ideias não implementadas não mudam nada  
	- Compartilhe ideias financeiras com as pessoas. Tentar seguir sozinho vai te levar à desistência.  
	- Duvide de fórmulas milagrosas. A receita do sucesso é a constância e a adaptação. Continue... Cada pequena mudança é relevante, mesmo que você não consiga seguir tudo nesse livro.  
	- Encontre confidentes financeiros pra discutir uns minutinhos a cada 15 dias. Se possível, crie um pequeno grupo de estudos financeiros.  
	- Siga estudando sobre dinheiro até se sentir confortável  
- Sugestões de leitura #[[Recomendações de livros]]  
	- Como se preocupar menos com dinheiro - John Armstrong  
	- Decisões econômicas: você já parou para pensar? - Vera Rita de Mello Ferreira  
	- Investimentos: como administrar melhor seu dinheiro - Mauro Halfeld  
	- Investimentos inteligentes - Gustavo Cerbasi  
	- Nudge: o empurrão para a escolha certa - Richard H. Thaler e Cass R. Sustein  
	- O livro da economia - de vários autores (Globo, 2013)  
	- Rápido e devagar: duas formas de pensar - Daniel Kahneman  
